<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="liuzw-PC-58" name="com.bj58.argo.ArgoExceptionTest" tests="4" failures="0" timestamp="9 May 2013 07:18:53 GMT" time="0.028" errors="0">
  <testcase name="testCause" time="0.001" classname="com.bj58.argo.ArgoExceptionTest"/>
  <testcase name="testBoth" time="0.025" classname="com.bj58.argo.ArgoExceptionTest"/>
  <testcase name="testMessage" time="0.001" classname="com.bj58.argo.ArgoExceptionTest"/>
  <testcase name="testContext" time="0.001" classname="com.bj58.argo.ArgoExceptionTest"/>
</testsuite> <!-- com.bj58.argo.ArgoExceptionTest -->
